
version: '3'
services:
  book_catalog:
    image: $CONTAINER_REGISTRY.azurecr.io/book_catalog:$VERSION
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://hari_task9_1_user:A54Oah0F6fYlB0L6hfW34UJv5umvZZEf@dpg-crulb9ogph6c73akl270-a.oregon-postgres.render.com/hari_task9_1
    restart: "no"

  inventory_management:
    image: $CONTAINER_REGISTRY.azurecr.io/inventory_management:$VERSION
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://hari_task9_1_user:A54Oah0F6fYlB0L6hfW34UJv5umvZZEf@dpg-crulb9ogph6c73akl270-a.oregon-postgres.render.com/hari_task9_1
    restart: "no"